name: C++ CI/CD

on:
  push:
    branches:
      - main
      - feature/github_actions
    tags:
      - 'v*'
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate version.txt
        run: |
          if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
            echo "${GITHUB_REF_NAME}" > version.txt
          else
            echo "dev-build" > version.txt
          fi

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "3.22.0"

      - name: Setup C++ compiler (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y g++

      - name: Configure project
        run: cmake -B build

      - name: Build project
        run: cmake --build build --config Release

      - name: Run program (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: ./build/hello

      - name: Run program (Windows)
        if: matrix.os == 'windows-latest'
        run: .\build\Release\hello.exe
